---
title: "Mozzie/Spatial R21 project analysis pipeline"
author: "Kelsey Sumner"
date: "1/14/2019"
output: 
  html_document:
    toc: true
    number_sections: false
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    theme: lumen
    highlight: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Last Updated `r format(Sys.Date(), format="%m/%d/%Y")`


**Approach:** Using longitudinal samples from Webuye, Kenya, evaluate the life course of asymptomatic Plasmodium falciparum malaria infections.

**Data aggregation:** Three primary data set types: Targeted amplicon sequencing data, quantitative PCR results, and social demographic data. There are multiple data sets for each type. 


# **Data set cleaning and compilation**

## Created lab inventories of the human and mosquito samples the lab recieved 
* Compiled and updated the lab inventories for the human DBS and mosquito samples the lab recieved and processed throughout the past year.
    + Location of the raw, uncompiled lab inventories: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > lab_inventories > csv files`
    + Code to clean and compile thte lab inventories: `taylorlab/SpatialR21_project/code/miscellaneous/spat21_create_lab_inventory.R`
    + Location of the cleaned, compiled lab inventories: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > clean files`

## Human data set cleaning and compliation
* Received 5 social demographic data sets (1. human annual household data 2. human sleeping space data 3. human monthly follow-up data 4. human table household data (annual) 5. human sick visits data)
    + Location of raw, uncleaned data sets: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Human data > raw_files`
* Created through human DBS punching -> extraction -> qPCR a qPCR data set for the parasite densities in the human samples collected through monthly follow-up and sick visits.
    + Location of raw, uncleaned data set:`Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Human data > raw_files > qpcr_data`
* Cleaned the 6 human data sets:
    + Code for cleaning human social demographic data sets: `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_data_cleaning.R`
    + Code for cleaning human qpcr data set: `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_data_cleaning_qpcr.R`
    + Location of cleaned separate data sets: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Human data > spat21_clean_human_files`
        + Notes:
    1. *Recalculated parasitemia values for each duplicate for each participant by creating a new standard curve with only standards 1-8 (concentrations from 1-2000 parasites/uL). Originally, standard curve based on standards 1-10 (0.1-2000 parasites/uL).*
    2. *Censoring criteria for parasitemia:*
        - *Recoding of CT values:*
            - *CT values of 0 recoded to missing (NA).*
            - *CT values of “undetermined” recoded to missing (NA) – however, these really signify negative results.*
            - *CT values 0 < CT < 40 for human beta-tubulin (Hb) are considered valid detection.*
            - *CT values of 0 < CT < 40 for Plasmodium falciparum are considered valid detection UNLESS only one replicate amplifies Pf, then the replicate that amplified has to have CT values of 0 < CT < 38 for Plasmodium falciparum to be considered valid.*
            - *Check that the standards (especially the first few) have amplified for human beta-tubulin and Plasmodium falciparum.*
        - *CT value censoring rules:*
            - *Pf positive via PCR:* 
                - *If 2 replicates amplified Pf: Pf CT values 0 < CT < 40*
                - *If 1 replicate amplified Pf: Pf CT values 0 < CT < 38*
            - *Pf negative via PCR: Pf CT undetermined (or Pf CT > 38 if one replicate), Hb CT values 0 < CT < 40*
            - *Pf missing via PCR: Pf CT values of 0 or sample not tested with PCR, Hb CT undetermined or 0 or sample not tested for PCR*
    3. *Rules for determining if participant is positive/negative/missing for Pf parasitemia:*
        - *If 1 replicate Pf positive per criteria above, used that replicate's standardized parasitemia for the participant to create combined parasitemia. Sample is positive for Pf in pf_pcr_infection_status variable.*
        - *If both replicates Pf positive per criteria above, averaged the replicates standardized parasitemia for the participant to create combined parasitemia. Sample is positive for Pf in pf_pcr_infection_status variable.*
        - *If both replicates Pf negative per criteria above, parasitemia is missing for combined parasitemia. Sample is negative for Pf in pf_pcr_infection_status variable.* 
        - *If both replicates missing via PCR per criteria above, parasitemia is missing for combined parasitemia. Sample is missing data for Pf in pf_pcr_infection_status variable.*  
* Merged the human data sets that could be merged:
    + Code for merging human social demographic data sets (enrollment table, monthly follow-up, sick follow-up): `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_data_cleaning_merge.R`
    + Code for merging merged human social demographic data set (enrollment table, monthly follow-up, sick follow-up) with cleaned qpcr data set (with 34 samples to have repeated qpcr removed): `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_merge_human_followup_and_qpcr_NEW_METHOD.R`
    + Code for merging merged human social demographic and qpcr data set (with samples to have repeated qpcr removed) to the qpcr data set containing just the 34 samples that were repeated for qpcr: `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_merge_repeated_qpcr_samples.R` and :`taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_merge_qpcr_social_data_FINAL_with_redo.R`
    + Code for cleaning final human merged data set for dissertation use. We first did: `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_clean_final_human_data_set.R` Then we did: `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_final_clean_merged_data.R`
    + Location of cleaned merged data sets: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Human data > spat21_clean_human_files > merged_files > final merged data`
       + Notes:
    1. *Reran qpcr for 34 human samples that had duplicate IDs in the lab inventory. Merged these into the data set later on, which is why have two merges with qpcr data.*
    2. *The DBS qpcr IDs were sometimes printed days up to 6 days prior to the day they were actually collected, so the DBS qpcr IDs sometimes contain dates that are up to 6 days prior to the social demographic (monthly follow-up) date. Used the social demographic (monthly or sick follow-up) date for the actual date of the disease onset in the analysis.*
    3. *59 samples did not have dates that fell within the 6 day period described in note 2 but were likely typos and were recoded in the data set. After this recoding, was able to merge all but 58 human qpcr DBS samples.*
    4. *Were missing some human DBS samples (some social demographic data did not having a matching DBS), so there was a total of 96 observations removed because of: 1) DBS didn't merge into the data set or 2) DBS was missing for social demographic observation, giving a total of 2823 observations with merged in and matching DBS.*
* Enforced follow-up censoring criteria on final merged data set one more time. 
    + Applied censoring criteria of having to have DBS merge in, have at least 2 monthly follow-up visits, and be >1 year old to be in final data set. 
    + Code for applying this censoring criteria to final merged data set: `taylorlab/SpatialR21_project/code/human_data_cleaning/spat21_make_final_censored_data_set.R`
    + Location of final data set for dissertation use: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Human data > spat21_clean_human_files > merged_files > final merged data > spat21_human_final_censored_data_for_dissertation_15JUL2019.rds`
    + Notes:
    1. *Removed some 4 participants that were <1 year old for entire follow-up period after data merging and 3 participants that had <2 months total follow-up after data merging.*
    2. *Some participants had observations removed so they didn't enter the study until they were at least 1 year old.*
    3. *Ended up with a total of 236 participants and 2799 observations.*
    

  
## Mosquito data set cleaning and compilation
* Received 2 descriptive data sets (1. culex and anopheles aggregate information 2. female Anopheles individual-level information)
    + Location of raw, uncleaned data sets: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Mosquito data > raw data`
* Created through mosquito DNA extraction -> qPCR a qPCR data set for the parasite densities in the female Anopheles mosquito head and abdomen samples collected through weekly household follow-up visits.
    + Location of raw, uncleaned data set:`Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Mosquito data > raw data`
* Cleaned the 2 female Anopheles data sets: 
    + Code for cleaning 2 female Anopheles data sets: `taylorlab/SpatialR21_project/code/mosquito_data_cleaning/spat21_data_cleaning_mosquitoes.R`
    + Location of cleaned separate data sets: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Mosquito data > clean data`
* Merged the 2 female Anopheles data sets to create one wide format (each row is a different mosquito - head and abdomen for that mosquito are placed on that same row)
    + Code for merging the data sets: `taylorlab/SpatialR21_project/code/mosquito_data_cleaning/spat21_data_merging_mosquitoes.R`
    + Location of the cleaned merged data set: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Mosquito data > clean data > merged_data`
* Pulled out the qpcr + mosquitoes for Betsy for sequencing.
    + Code for identifying which mosquitoes were qpcr +: `taylorlab/SpatialR21_project/code/mosquito_data_cleaning/spat21_pcr_pos_id_mosquitoes.R`
    + Location of the qpcr + mosquito IDs: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Final Data Sets > Final Cohort data June 2017 to July 2018 > Mosquito data > Betsy data`
+ Notes:
    1. *There were 3 mosquitoes in the qPCR data set that didn't merge the the female Anopheles descriptive data set.*
    2. *There were 17 mosquitoes in the female Anopheles descriptive data set that didn't merge with the qPCR data set because they were contaminated in lab processing or not received in the lab.*
    3. *Mosquitoes were considered Pf + by qPCR if had any Pf CT value in either head or abdomen from 0 < CT < 40.*
    4. *Mosquitoes were considered Hb + by qPCR if had any Hb CT value in either head or abdomen from 0 < CT < 40.*


# **Aim 1A: Time-to-event analysis for symptomatic malaria**
* Looked at consecutive follow-up time to determine if we should impute follow-up time for aim 1A. Determined that we do not want to impute follow-up time for now. 
    + Code for looking at consecutive follow-up: `taylorlab/SpatialR21_project/code/aim1a_analyses/spat21_conseuctive_followup.R`
    + Location of consecutive follow-up table: `Dissertation Materials > SpatialR21 Grant > Final Dissertation Materials > Aim 1A > Consecutive Follow-up Tables`
  
  
  